import{i as d,S as b,a as L}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const u="/goit-js-hw-12/assets/bi_x-octagon-ddf7add7.svg",a={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),btnLoadMore:document.querySelector(".btn-load-more")};let c="",w=c,g=1,m=0;const y=15;async function f(){const n="https://pixabay.com/api/?key=42132229-e88b92984f0d2a7001cb07c65";try{const{data:s}=await L.get(n,{params:{image_type:"photo",orientation:"horizontal",safesearch:"true",q:c,per_page:y,page:g}});return s}catch(s){console.log(s)}}a.form.addEventListener("submit",v);async function v(e){if(e.preventDefault(),q(),c=e.target.elements.query.value.trim(),g=1,a.gallery.innerHTML="",i(),w!=c){try{const t=await f();if(c)parseInt(t.totalHits)>0?(P(),p(t.hits),m=t.totalHits,h(),i()):(d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red",messageColor:"white",messageSize:"16px",iconColor:"white",iconUrl:u,color:"white",timeout:2e3}),i());else{d.warning({message:"Sorry, you forgot to enter a search term. Please try again!",position:"topRight",messageSize:"16px",timeout:2e3}),i();return}}catch{d.error({message:"Error",position:"topRight",backgroundColor:"red",messageColor:"white",messageSize:"16px",iconColor:"white",iconUrl:u,color:"white",timeout:2e3}),i()}a.btnLoadMore.addEventListener("click",C),e.target.reset()}}function S({largeImageURL:e,webformatURL:t,tags:n,likes:s,views:o,comments:r,downloads:l}){return`<a class="gallery-link" href="${e}"><img class="gallery-image" src="${t}" alt="${n}"/>
  <div class="gallery-review">
  <div class="gallery-review-item"><b>Likes</b> <span>${s}</span></div>
  <div class="gallery-review-item"><b>Views</b> <span>${o}</span></div>
  <div class="gallery-review-item"><b>Comments</b> <span>${r}</span></div>
  <div class="gallery-review-item"><b>Downloads</b> <span>${l}</span></div>
  </div></a>
    `}let M=new b(".gallery a",{showCounter:!1,captionDelay:250,captions:!0,captionsData:"alt",captionPosition:"bottom"});function p(e){const t=e.map(S).join("");a.gallery.insertAdjacentHTML("beforeend",t),M.refresh()}async function C(){i(),g+=1;const e=await f();p(e.hits),h(),i(),R()}function h(){const e=Math.ceil(m/y);console.log(e);const t=e<=g;console.log(t),t&&(a.btnLoadMore.classList.add("hidden"),d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageSize:"16px",timeout:2e3}))}function i(){a.loader.classList.toggle("hidden")}function P(){a.btnLoadMore.classList.toggle("hidden")}function q(){!a.btnLoadMore.classList.contains("hidden")&&a.btnLoadMore.classList.add("hidden")}function E(){return document.querySelector(".gallery-link").getBoundingClientRect().height}function R(){const e=E();window.scrollBy(0,e*2)}
//# sourceMappingURL=commonHelpers.js.map
