import{i as l,S as L,a as w}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const u="/goit-js-hw-12/assets/bi_x-octagon-ddf7add7.svg",a={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),btnLoadMore:document.querySelector(".btn-load-more")};let g="",d=1,m=0;const y=15;async function f(){const n="https://pixabay.com/api/?key=42132229-e88b92984f0d2a7001cb07c65";try{const{data:s}=await w.get(n,{params:{image_type:"photo",orientation:"horizontal",safesearch:"true",q:g,per_page:y,page:d}});return s}catch(s){console.log(s)}}a.form.addEventListener("submit",v);async function v(t){t.preventDefault(),C(),g=t.target.elements.query.value.trim(),d=1,a.gallery.innerHTML="",i();try{const o=await f();if(g)parseInt(o.totalHits)>0?(b(),p(o.hits),m=o.totalHits,h(),i()):(l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red",messageColor:"white",messageSize:"16px",iconColor:"white",iconUrl:u,color:"white",timeout:2e3}),i());else{l.warning({message:"Sorry, you forgot to enter a search term. Please try again!",position:"topRight",messageSize:"16px",timeout:2e3}),i();return}}catch{l.error({message:"Error",position:"topRight",backgroundColor:"red",messageColor:"white",messageSize:"16px",iconColor:"white",iconUrl:u,color:"white",timeout:2e3}),i()}a.btnLoadMore.addEventListener("click",P),t.target.reset()}function S({largeImageURL:t,webformatURL:o,tags:n,likes:s,views:e,comments:r,downloads:c}){return`<a class="gallery-link" href="${t}"><img class="gallery-image" src="${o}" alt="${n}"/>
  <div class="gallery-review">
  <div class="gallery-review-item"><b>Likes</b> <span>${s}</span></div>
  <div class="gallery-review-item"><b>Views</b> <span>${e}</span></div>
  <div class="gallery-review-item"><b>Comments</b> <span>${r}</span></div>
  <div class="gallery-review-item"><b>Downloads</b> <span>${c}</span></div>
  </div></a>
    `}let M=new L(".gallery a",{showCounter:!1,captionDelay:250,captions:!0,captionsData:"alt",captionPosition:"bottom"});function p(t){const o=t.map(S).join("");a.gallery.insertAdjacentHTML("beforeend",o),M.refresh()}async function P(){i(),b(),d+=1;const t=await f();p(t.hits),h(),i(),x()}function h(){Math.ceil(m/y)<=d?(a.btnLoadMore.classList.add("hidden"),l.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight",messageSize:"16px",timeout:2e3})):a.btnLoadMore.classList.remove("hidden")}function i(){a.loader.classList.toggle("hidden")}function b(){a.btnLoadMore.classList.toggle("hidden")}function C(){!a.btnLoadMore.classList.contains("hidden")&&a.btnLoadMore.classList.add("hidden")}function q(){return document.querySelector(".gallery-link").getBoundingClientRect().height}function x(){const t=q();window.scrollBy(0,t*2)}
//# sourceMappingURL=commonHelpers.js.map
